### ISSUE TITLE
Few Question in using devzat

### ISSUE THREAD

**Issue by B17w153** [quackduck/devzat#164]
- The picture that shows in terminal have a really unclear look, can we make it looks more clearer?and also sometimes sending markdown picture would do no shit like the picture doesnt even show in the terminal,whichi should be the the connection error or ish.
e.g.
![image](https://github.com/quackduck/devzat/assets/134407644/bcbf7d71-f4f1-4abc-bbcc-482834db0d5b)
![image](https://github.com/quackduck/devzat/assets/134407644/4e8f8a79-e509-4b2e-8747-ef26e70c8dbb)
it looks even worse in phone
![image](https://github.com/quackduck/devzat/assets/134407644/71a256f2-7870-4f65-ac5b-650e6591dba8)

- is there any way that we can save the messages that ever showed up in the chatroom into a log file like chat.log? i often can't catch up with my friends.

**Comment by quackduck** [comment]
Hey, sorry for the late response.

Unfortunately the pictures are blurry because we _are_ still limited by the text interface that a terminal is. Each pixel is actually a unicode character colored with ANSI color codes.

Sometimes pictures may not show up if they are too big (file size or dimensions)

There's a few ways you could enable chat logging. If you connect Devzat to a Discord server, all your messages will be posted there and you pretty much have a complete log on Discord. You could also make a devzat plugin in javascript, rust or go that saves all messages. Let me know if you want details on that.
